Updated/added doc to spark_run

diff --git a/spark_run b/spark_run
--- a/spark_run
+++ b/spark_run
@@ -1,47 +1,56 @@
 #!/bin/bash
-#======================================
-# Run a spark application on the cluster
-# Ensure that master/nodes have been started
-#======================================
+# 
+# spark_run -d outputDir -C Class assembly.jar
+#
+# spark_run -v[erbose] -L[ogsCopied] [-M slaveMem] [-N AppName] [-v(erbose)] -d outputDir -C Class assembly.jar
+# 
+# Run a spark application, assembly.jar, on the cluster. Time it, and
+# extract the ganglia metrics for the execution to -d outputDir.
+# 
+#	Optionally specify slaveMem, AppName, and (main) Class
+# 
+#	If no classname is given, you will be prompted for one, since it is
+# the entry point to Spark execution (main).
+# 
+# This script will call . spark_vars for global definitions.
+# =================================================
+# Author: Michael B Hynes, mbhynes@uwaterloo.ca
+# License: GPL 3
+# Creation Date: Tue 17 Feb 2015 10:45:57 PM EST
+# Last Modified: Wed 18 Feb 2015 12:18:24 AM EST
+# =================================================
 
+SLAVE_MEM_ARG=""
+SCRIPT_NAME=$(basename $0)
+
+msg () {
+	echo "$SCRIPT_NAME: $@" 1>&2
+}
+warn () {
+	msg WARNING: $@
+}
+error () {
+	msg ERROR: $@
+}
 # this function only works if you clean out the log directory
 get_worker_logs()
 {
 	key=$(date +%Y%m%d)
 	src=$SPARK_WORKER_LOG_DIR
 	log=$(ls -1t $src | head -n 1)
-	if ! echo $log | grep -qm 1 "$key"; then
-		echo "WARNING: log directory $log has incorrect timestamp." 1>&2
+	if ! grep -qm 1 "$key" <<< "$log"; then
+		warn "WARNING: log directory $log has incorrect timestamp."
 	fi
 	echo $SPARK_WORKER_LOG_DIR/$log
 }
-
-if (($#==0)); then
-	cat <<-EOF
-
-	usage: $(basename $0) [-d outputDir] [-M slaveMem] [-N AppName] [-v(erbose)] [-C Class] package.jar"
-
-	Run package.jar on the cluster.
-	Optionally specify slaveMem, Appname, and (main) Class
-
-	If no class is given, you will be prompted for one.
-
-	Ensure that master/nodes have been started.
-
-EOF
-	exit 0
-fi
 
 get_time() {
 	date +%s
 }
 
-SLAVE_MEM_ARG=""
-
 # parse commandline arguments
 GETOPT_STRING="vj:C:M:N:d:L"
-while getopts $GETOPT_STRING opt
-do
+while getopts $GETOPT_STRING opt; do
 	case $opt in
 		M)
 			SLAVE_MEM="$OPTARG"
@@ -62,19 +71,19 @@ do
 			GET_LOGS="true"
 			;;
 		:)
-			echo "-$opt requires argument"
+			error "-$opt requires argument"
 			exit 1
 			;;
 		\?) 
-			echo "invalid option -$opt" 1>&2
+			warn "invalid option -$opt"
 			;;
 	esac
 done
 shift $((OPTIND-1))
 
 if (($# == 0)); then
-	echo "$(basename $0): <opts> package.jar"
-	echo "You must specify the jar to send to Spark."
+	error "No jar specified."
+	disp_opts -h -n 30 $0 2>/dev/null
 	exit 1
 fi
 
@@ -84,42 +93,31 @@ JAR=$1
 . spark_vars
 
 if [ -z "$JAR" ] || [ ! -f "$JAR" ]; then
-	echo "jar: $JAR" 
-	echo "could not be found or is not a regular file"
+	error "jar: $JAR could not be found or is not a regular file"
 	exit 1
 fi
+
 if [ -z "$OUT_DIR" ]; then
-	echo "You should specify the output directory for logs/ganglia info with [-d dir]"
+	error "-d outputDir unspecified; exiting"
 	exit 1
 fi
 
 if [ -z "$CLASS" ]; then
+	warn "Classname unspecified"
 	read -p "Enter classname >>> " CLASS
 fi
 
 if [ -z "$NAME" ]; then
-	NAME=$(echo $CLASS | tr 'A-Z' 'a-z')-$t_start
+	NAME=$(tr 'A-Z' 'a-z' <<< "$CLASS")-$t_start
 fi
 
 if [ -z "$SLAVE_MEM" ]; then
 	SLAVE_MEM="$SPARK_MAX_MEM"
 fi
 
+msg "Rnning $JAR:$CLASS on the cluster and saving to $OUT_DIR."
 t_start=$(get_time)
-
-if [ -z "$VERBOSE" ]; then
-	spark-submit \
-		--deploy-mode $SPARK_DEPLOY_MODE \
-		--name $NAME \
-		--class $CLASS \
-		--master $SPARK_MASTER_URL \
-		--driver-memory $SPARK_DRIVER_MEM \
-		--executor-memory $SLAVE_MEM \
-		$JAR \
-		$@  \
-		1> >(tee $SPARK_LOG_STDOUT) \
-		2> $SPARK_LOG_STDERR
-else
+if [ -n "$VERBOSE" ]; then
 	# VERBOSE option: use tee to copy stderr to stdout
 	spark-submit \
 		--deploy-mode $SPARK_DEPLOY_MODE \
@@ -131,37 +129,52 @@ else
 		$JAR \
 		$@  \
 		1> >(tee $SPARK_LOG_STDOUT) \
-		2> >(tee $SPARK_LOG_STDERR)
+		2> >(tee $SPARK_LOG_STDERR | grep 'Job [[:digit:]]+ finished')
+else
+	spark-submit \
+		--deploy-mode $SPARK_DEPLOY_MODE \
+		--name $NAME \
+		--class $CLASS \
+		--master $SPARK_MASTER_URL \
+		--driver-memory $SPARK_DRIVER_MEM \
+		--executor-memory $SLAVE_MEM \
+		$JAR \
+		$@  \
+		1> >(tee $SPARK_LOG_STDOUT) \
+		2> $SPARK_LOG_STDERR
 fi
+t_end=$(get_time)
 
 STATUS="$?"
 
 if [ "$STATUS" -ne 0 ]; then
-	cat <<-EOF
-
-	FAILURE: spark-submit exited with status "$STATUS" 1>&2
-	Exiting catastrophically. 1>&2
-	You may have to clean up "$SPARK_LOG_DIR/$NAME/" 1>&2
-
+# 	cat <<EOF 
+# FAILURE: spark-submit exited with status "$STATUS" 
+# Exiting catastrophically. 
+# You may have to clean up "$SPARK_LOG_DIR/$NAME/" 
+# EOF 
+	cat <<EOF
+FAILURE: spark-submit exited with status "$STATUS" 
+Exiting catastrophically. 
+You may have to clean up "$SPARK_LOG_DIR/$NAME/" 
 EOF
 	JOB_FAILED="true"
 fi
 
-sleep $SPARK_RUN_DELAY
-t_end=$(get_time)
-
+# this doesn't work in 1.3-SNAPSHOT
 # get the spark directory $NAME-120398429103, (CLASS-timestamp)
-spark_dir=$(ls -d $SPARK_LOG_DIR/$NAME-* 2>/dev/null)
+# spark_dir=$(ls -d $SPARK_LOG_DIR/$NAME-* 2>/dev/null)
 
 # rename to output directory
 if [ -n "$OUT_DIR" ]; then
 
-	if [ -d "$OUT_DIR" ] && [ -d "$spark_dir" ]; then
-		mv $spark_dir/* $OUT_DIR
-		rmdir $spark_dir
-	else
-		mv $spark_dir $OUT_DIR
-	fi
+	# this doesn't work in 1.3-SNAPSHOT
+	# if [ -d "$OUT_DIR" ] && [ -d "$spark_dir" ]; then
+	# 	mv $spark_dir/* $OUT_DIR
+	# 	rmdir $spark_dir
+	# else
+	# 	mv $spark_dir $OUT_DIR
+	# fi
 
 	mv $SPARK_LOG_STDERR $OUT_DIR
 	mv $SPARK_LOG_STDOUT $OUT_DIR
@@ -176,8 +189,7 @@ if [ -n "$GET_LOGS" ]; then
 
 	if [ -d "$log_dir" ]; then
 		echo "Copying $log_dir/ to $SPARK_WORKER_LOGS/" 1>&2
-		# rsync -az --exclude='*.jar' $log_dir $SPARK_WORKER_LOGS
-		cp -r $log_dir $SPARK_WORKER_LOGS
+		rsync -az --exclude='*.jar' "$log_dir/" $SPARK_WORKER_LOGS
 	fi
 fi
 
@@ -189,10 +201,7 @@ echo $t_end >> $SPARK_LOG_TIME
 echo $STATUS > "$SPARK_EXIT_STATUS"_"$STATUS"
 
 # compile ganglia metrics
-if [ ! -d "$GANGLIA_DATA_DIR" ]; then
-	mkdir "$GANGLIA_DATA_DIR"
-fi
-
+mkdir -p "$GANGLIA_DATA_DIR"
 cd "$GANGLIA_DATA_DIR"
 rrdcsv $GANGLIA_METRICS 1>$GANGLIA_NODE_ORDER 2>$GANGLIA_LOG_STDERR
 cd "$OLD_PWD"
